### ISSUE TITLE
Updated design

### ISSUE THREAD

**Issue by mudar** [mudar/patinermontreal.ca#1]
Hi @jonathanbrun @jpmckinney

I'm starting this as an issue, hoping it'll be more efficient than emails. 

After updating the leaflet library, I started updating the design. Here's a first screenshot.

![design 2014 v0](https://cloud.githubusercontent.com/assets/497949/3997156/d59669d4-293c-11e4-84da-8cda8f116a58.jpeg)

I still need to work on the **bottom** control bar, but the main idea is there. how do you like it? do we want to update the design or shall we stay with the one we have?

Open questions:
1. I've replaced the red by blue. I think it's feels more like _winter_! 
2. I'm considering removing the **rink-type** color code: mauve/blue/green to a **single** color (on/off). Type distinction would remain there based only on the shape (triangle/square/circle). 

The design is bootstrap/responsive:
![design 2014 v0 responsive](https://cloud.githubusercontent.com/assets/497949/3997259/ec9e13ba-293d-11e4-9e2e-1cee1720125a.jpeg)

The social icon does a slideToggle() on the social box. Mainly because the top-bar was quite cluttered with all that information.

The current work-in-progress is on my repo in a new **design-2014** branch.

**Comment by jpmckinney** [comment]
Looking good!

**Comment by jonathanbrun** [comment]
looks great!

On 2014-08-21 10:23 AM, Mudar Noufal wrote:

> Hi @jonathanbrun https://github.com/jonathanbrun @jpmckinney 
> https://github.com/jpmckinney
> 
> I'm starting this as an issue, hoping it'll be more efficient than 
> emails.
> 
> After updating the leaflet library, I started updating the design. 
> Here's a first screenshot.
> 
> design 2014 v0 
> https://cloud.githubusercontent.com/assets/497949/3997156/d59669d4-293c-11e4-84da-8cda8f116a58.jpeg
> 
> I still need to work on the _bottom_ control bar, but the main idea is 
> there. how do you like it? do we want to update the design or shall we 
> stay with the one we have?
> 
> Open questions:
> 1. I've replaced the red by blue. I think it's feels more like /winter/!
> 2. I'm considering removing the _rink-type_ color code: 
> mauve/blue/green to a _single_ color (on/off). Type distinction would 
> remain there based only on the shape (triangle/square/circle).
> 
> The design is bootstrap/responsive:
> design 2014 v0 responsive 
> https://cloud.githubusercontent.com/assets/497949/3997259/ec9e13ba-293d-11e4-9e2e-1cee1720125a.jpeg
> 
> The social icon does a slideToggle() on the social box. Mainly because 
> the top-bar was quite cluttered with all that information.
> 
> The current work-in-progress is on my repo in a new _design-2014_ branch.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mudar/patinermontreal.ca/issues/1.

## 

Jonathan
http://jonathanbrun.com
514-712-0637

**Comment by mudar** [comment]
Updated screenshots
**Icons OFF**
![icons off](https://cloud.githubusercontent.com/assets/497949/4111813/9e0bfc1a-3213-11e4-97dc-74e842af44d1.jpeg)

**Icons ON + Rink info**
![icons on rink info](https://cloud.githubusercontent.com/assets/497949/4111814/a2661cbe-3213-11e4-95b1-330b8981336d.jpeg)

**Mobile responsive**
![mobile nexus 5](https://cloud.githubusercontent.com/assets/497949/4111815/a564773a-3213-11e4-8981-090c2d8934d8.png)

I still have some minor javascript issues related to the display of RinkInfo and toggling the social top-right box. Will create other issues on github.

**Comment by jonathanbrun** [comment]
looks great!

On 2014-09-01 10:10 PM, Mudar Noufal wrote:

> Updated screenshots
> _Icons OFF_
> icons off 
> https://cloud.githubusercontent.com/assets/497949/4111813/9e0bfc1a-3213-11e4-97dc-74e842af44d1.jpeg
> _Icons ON + Rink info *_
> icons on rink info 
> https://cloud.githubusercontent.com/assets/497949/4111814/a2661cbe-3213-11e4-95b1-330b8981336d.jpeg
> *_Mobile responsive_
> mobile nexus 5 
> https://cloud.githubusercontent.com/assets/497949/4111815/a564773a-3213-11e4-8981-090c2d8934d8.png
> 
> I still have some minor javascript issues related to the display of 
> RinkInfo and toggling the social top-right box. Will create other 
> issues on github.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mudar/patinermontreal.ca/issues/1#issuecomment-54088992.

## 

Jonathan
http://jonathanbrun.com
514-712-0637

**Comment by mudar** [comment]
Following issue #7 I've replaced the FB-like and Tweet buttons by 3 HTML buttons that open share links on FB, Twitter and G+.
![share buttons](https://cloud.githubusercontent.com/assets/497949/4152742/9f5b7132-3451-11e4-86e2-5e37b478fb1a.jpeg)

**Comment by mudar** [comment]
Displaying the rink's phone number and the _contact the city_ block.
I've used a green (i) icon to the left of the paragraph, but I also like the comment and lightbulb icons here: http://fortawesome.github.io/Font-Awesome/icons/

![call_to_action](https://cloud.githubusercontent.com/assets/497949/4175542/776ee652-35d9-11e4-87b2-6c261f6044ca.jpeg)
