### ISSUE TITLE
JS: Toggle Kinds when deselecting favorites

### ISSUE THREAD

**Issue by mudar** [mudar/patinermontreal.ca#6]
I'm a bit lost here! 

In the bottom control buttons, the original version used to restore selected rink **Kinds** when deselecting **Favorites**. Not sure if the same was applied to **Statuses**. 

In the new version, layout has changed slightly, so the **icon** class isn't at the same level, so restoring selection is broken.

Also, I'm not sure how this interacts (if any) with the URL change.

Any idea?

**Comment by jpmckinney** [comment]
The easiest solution is to restore the `.icon` class to the same level as before, and to use new CSS classes if you need to for the changes that you made.

What URL changed?

**Comment by mudar** [comment]
By URL change, I meant the windowLocation change following button click, and how that triggers markers show/hide on the map. Are the markers toggled on control button click or on windowLocation change?

However, things might be ok! I've checked the original version and it seems similar.

Example: 
1. enabled are PP PSE (kinds) and resurface (status): /f/patin-libre/sports-dequipe/resurface
2. When I click on favorites, window location becomes /favories Control icons are **not toggled** for "active", except for Favorites which becomes active. 
3. two options from here
   - A. When I click again on favorites, **url reverts** to /f/patin-libre/sports-dequipe/resurface and favorites is not active any more (sounds good!)
   - B. Instead of disabling favorites, let's say you click "arrose". location becomes /f/patin-libre/sports-dequipe/arrose/resurface and this **toggles-off** Favorites.

I was wondering about n.2: When you enable favorites, is that supposed to toggle any other control buttons? In the way 3B toggles-off favorites...

**Comment by jpmckinney** [comment]
"Favorites" is treated as a special mode. It remembers the last state before entering "favorites mode". So when you untoggle favorites, it restores the last state. If you select a new option, it modifies the last state and shows you the new state.

**Comment by mudar** [comment]
Things seem ok.

Entering Favorites mode doesn't toggle other control-icons.
When in in favorites mode, clicking any other control-icon toggles off the Favorites icon and leaves Favorites mode
