### ISSUE TITLE
FB app misconfigured?

### ISSUE THREAD

**Issue by mudar** [mudar/patinermontreal.ca#7]
Not sure if this is normal: https://apps.facebook.com/152478391528436/

> Error
> Sorry, the application you were using is misconfigured. Please try again later.

**Comment by jonathanbrun** [comment]
Not sure - I closed my FB account, not sure if the app was linked. 
frankly, I think we can ignore facebook integration - we just want 
people to like patinermontreal.com in such a way that it appears on 
their newsfeed and generates promotion for us, but that is about it in 
my opinion.

On 2014-09-01 11:53 PM, Mudar Noufal wrote:

> Not sure if this is normal: https://apps.facebook.com/152478391528436/
> 
> ```
> Error
> Sorry, the application you were using is misconfigured. Please try
> again later.
> ```
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mudar/patinermontreal.ca/issues/7.

## 

Jonathan
http://jonathanbrun.com
514-712-0637

**Comment by mudar** [comment]
Sounds good to me!

I'll replace the FB button by a simple share link that will open facebook in a new tab. No app-ID required.
